baseURL = "https://fangqiuhang.github.io/RFC9000_Chinese_Translation/"
languageCode = "cn"

title = "RFC9000中文"
defaultContentLanguage  = "cn"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
  #externalTitle = "RFC9000 QUIC：一种基于UDP的安全多路复用传输协议"
  sidebarColor = "quic"
  customCss = ["css/RFC9000.css"]

[[resources]]
  src = "**.svg"

[[menu.shortcuts]]
  name = "RFC8999 QUIC版本通用属性"
  weight = 10
  [menu.shortcuts.Params]
    lateralurl = "/RFC8999_Chinese_Translation/"

[markup]
  #defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
